### ISSUE TITLE
Evaluations per joule?

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#11]
Shouldn't we use evaluations per joule used to compare the different devices?

**Comment by ccottap** [comment]
All devices perform the same number of evaluations so using total energy per run is equivalent.

**Comment by JJ** [comment]
No, they don't if they run until the solution is found.

**Comment by fcofdezdevega** [comment]
Same number of evaluations when the solution is not reached.

Anyway, every device doing the same given same random seeds and same compiler and libraries is employed.

**Comment by ccottap** [comment]
And also the same number of evaluations when it is reached. They do the same always.

**Comment by JJ** [comment]
They can't have the same number of evaluations if the population is
different. Different population sizes will yield a different number of
evaluations to solution.
```
On the other hand, and given the influence of computing time in the total
amount of energy consumed by the algorithm, we configured the main loop of
the algorithm to finish when the solution is found
```
(BTW, that "on the other hand" is too close to another in the previous
paragraph). If you are configuring it for running for a number of
evaluations, it's a different thing from what you say in the paper. Even if
it is a *max* number of evaluations, it will use *less* if it finds the
solution. So reporting evaluations/joule makes sense, at the end of the day
that is what you are looking for. Which device spends the most joule when
doing the measure (evaluations) you compare algorithms with?

**Comment by JJ** [comment]
Ah, OK, I see what you mean. Anyway they will need a different number of
evaluations for different populations and it still will be interesting to
report that for the sake of comparison of devices. Evaluations, not
population, is still something you can use to compare different algorithms.
Population is just a parameter.

**Comment by fcofdezdevega** [comment]
jj, you said:

Shouldn't we use evaluations per joule used to compare the different devices?

And we refer to devices.

**Comment by fcofdezdevega** [comment]
We don't have enough time to do more things/comparisons/graphs....

Let's simply polish what we have and submit it.

**Comment by JJ** [comment]
I see that fig 2B is more or less the same. However, you are using
"approximation ratio", which is not something that you can measure
algorithms with, different fitnesses will have a different approximation
ratio. What I'm saying is that maybe it would be reasonable to use a lineal
or algorithmic #evaluations scale to fit that, to see how consumption
changes with the number of evaluations.

**Comment by JJ** [comment]
We are three days to deadline, don't think it's a big deal to change that a
bit. It's just a matter of counting the number of evaluations for every
run, can be done in any computer, since results are the same.

**Comment by fcofdezdevega** [comment]
Go ahead JJ ;-)  all the experimental data are available;  If you think something must be added, please, do it similarly as Carlos did when he considered of interest to include graphs.  For me tables were enough, given that I didn't have the time to produce the graphics, but Carlos help was more than welcome.

Unfortunately, I don't have more time for this paper, since I have plenty of clases today and I'm traveling until tuesday :-(

Carlos can provide you with all the data collected.

**Comment by JJ** [comment]
Are evaluations per run available?

**Comment by ccottap** [comment]
Quite on the contrary, the approximation ratio is a performance measure that can be compared and understood not only among different algorithms but even across different problems. In addition, it is more meaningful than fitness evaluations because the algorithm does not progress at a constant rate and hence attaining a certain improvement in approximation can amount to a much larger energy spent. This provides a natural link to non-FPTAS scenarios.

Measuring the energy cost of a fitness evaluation might have some interest when analyzing problems instances of different sizes, but it ought to be independent of population sizes. The idea of computing energy consumption per unit of computation is already captured by power anyway.

**Comment by JJ** [comment]
OK, whatever. We don't have time anyway, so let ir rest.
