### ISSUE TITLE
Can we also comment on the abstract?

### ISSUE THREAD

**Issue by JJ** [frchavez/PPSN_Consumo_2016#4]
The abstract does not match the title and instead talks about a new way of measuring the performance of evolutionary algorithms. As far as I have been able to gather, there is no other paper that measures evolutionary algorithms according to performance. Most energy-aware algorithms are applied to things that take lots of energy like mobile ad-hoc networks. So I guess the *new* part is true. However, that is not what we are doing in this paper. As far as we understand it, we are measuring different *devices*, not *algorithms* So once again the title (as indicated in #3 ) and the abstract must match what we are actually doing and with each other. Please @pacastillo and @ccottap comment.

**Comment by ccottap** [comment]
Agree. I think the storyline should be about the relevance of energy consumption, not just from the general standpoint of green computing but also from the point of view of emergent computational environments (dynamic, heterogeneous, etc. linking with ephemeral computing). From this, we argue the relevance of tackling this issue in EAs (because they are very well suited to these environments). Hence this seminal work in which we take the initial steps towards energy-aware EAs by analizing their energy profile in light of their parameterization.

**Comment by JJ** [comment]
That would be OK for me. Can you rewrite the abstract along those lines?

**Comment by ccottap** [comment]
Abstract rewritten. It is more an argumental skeleton than a final abstract though: it would need some additions with the actual results/conclusions once the latter are included in the paper. I thus keep this issue open.

**Comment by JJ** [comment]
The abstract should spoil conclusions a bit, or at least say something about them. It stops short of doing so.

**Comment by fcofdezdevega** [comment]
Done
